version: "3.8"

services:
  db:
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-data}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123qwe}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123qwe}
      MYSQL_USER: ${MYSQL_USER:-admin}
