name: Github CI

on:
  push:
    branches: [ "main", "develop", "github-workflow" ]
  pull_request:
    branches: [ "main", "develop", "github-workflow" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        make build
        docker image ls